# Generated by Django 3.0.8 on 2021-06-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0003_remove_setting_max_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='advance_booking',
        ),
    ]
