# Generated by Django 3.0.8 on 2021-06-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table_booker", "0004_remove_setting_advance_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setting",
                to="table_booker.Restaurant",
            ),
        ),
    ]
