# Generated by Django 3.0.8 on 2021-06-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0005_auto_20210618_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='postcode',
        ),
    ]
