# Generated by Django 3.0.8 on 2021-06-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0006_remove_restaurant_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='table_booker.Restaurant'),
        ),
    ]
